spring.cloud.config.server:
  vault:
    port: 8200
    host: 127.0.0.1
    scheme: http
    authentication: TOKEN
    token: hvs.ZZqcl357guUzC92VOuJFYLqn
    backend: hackathon-organizer-secrets
    kv-version: 2
spring:
  profiles:
    active: vault
  application:
    name: config-server
server:
  port: 8888
