spring.cloud.config.server:
  vault:
    port: ${VAULT_PORT}
    host: ${VAULT_URL}
    scheme: http
    authentication: TOKEN
    token: hvs.ZZqcl357guUzC92VOuJFYLqn
    backend: hackathon-organizer-secrets
    kv-version: 2
spring:
  profiles:
    active: vault
  application:
    name: config-server
server:
  port: 8888
